sudo: required
language: python
python:
    2.7
before_script:
    - mkdir darksearch/logs
# Needs sudo...
install:
    - sudo apt-get install gunicorn
    - sudo pip install -r requirements.txt
script:
    sudo python dark_test.py
after_success:
    coveralls
